export const API_ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_REFRESH_REUSED: 'AUTH_REFRESH_REUSED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_UNAUTHENTICATED: 'AUTH_UNAUTHENTICATED',
  COURSE_NOT_PUBLISHED: 'COURSE_NOT_PUBLISHED',
  COURSE_SLUG_TAKEN: 'COURSE_SLUG_TAKEN',
  ENROLL_ALREADY: 'ENROLL_ALREADY',
  LESSON_MEDIA_NOT_READY: 'LESSON_MEDIA_NOT_READY',
  QUIZ_NOT_OPEN: 'QUIZ_NOT_OPEN',
  QUIZ_ALREADY_ANSWERED: 'QUIZ_ALREADY_ANSWERED',
  QUIZ_RUN_LOCKED: 'QUIZ_RUN_LOCKED',
  MEDIA_INVALID_TYPE: 'MEDIA_INVALID_TYPE',
  MEDIA_TOO_LARGE: 'MEDIA_TOO_LARGE',
  MEDIA_SIZE_MISMATCH: 'MEDIA_SIZE_MISMATCH',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
